### ISSUE TITLE
How do we install this?

### ISSUE THREAD

**Issue by mehmetkursataydin** [magimetal/Synthwave-X-Jetbrains#2]
Manually, since it is not in the plugins market. I'd like to install this on Rider.

**Comment by bycym** [comment]
Okay, finally I've found out how to install it. So:
- Got to settings
- Editor > ColorScheme
- Click on the cogwheel next above the color scheme name
- Import scheme
- go to checkout or the folder where you downloaded.
- import the icls file
- apply
- do a winning dance!

**Comment by magimetal** [comment]
> Okay, finally I've found out how to install it. So:
> 
> * Got to settings
> * Editor > ColorScheme
> * Click on the cogwheel next above the color scheme name
> * Import scheme
> * go to checkout or the folder where you downloaded.
> * import the icls file
> * apply
> * do a winning dance!

Correcto!
