### ISSUE TITLE
is this broken now that the material plugin doesn't allow importing themes?

### ISSUE THREAD

**Issue by zachgrayio** [magimetal/Synthwave-X-Jetbrains#4]
so we're just left with the code color scheme now? :frowning:

**Comment by magimetal** [comment]
I haven't been using Material for a while now, it feels like it adds bloat. I've been just pairing with the High Contrast UI Theme for now. 

![image](https://user-images.githubusercontent.com/36491250/157563291-ba6334bf-a7c9-4413-b571-e7acf670b451.png)

I will look into resolving this for Material Theme if possible.

**Comment by magimetal** [comment]
Please see the updated readme regarding removing support for material ui as well as a recommended alternative theme.
